// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52d4IGTra0J33REeqwisaWkF4SoPtaqM',
    appId: '1:829328918053:web:5b1ca95f015971568b21cc',
    messagingSenderId: '829328918053',
    projectId: 'femclock',
    authDomain: 'femclock.firebaseapp.com',
    storageBucket: 'femclock.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXJ4XSTWJxRr85TYarhySCCUiVlFyzEI',
    appId: '1:829328918053:android:2d1e896e65a5644b8b21cc',
    messagingSenderId: '829328918053',
    projectId: 'femclock',
    storageBucket: 'femclock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6c8BBUKj2c0LQvpkZTbujFpA-ZkCVpsI',
    appId: '1:829328918053:ios:1cf7f2de7ea6089f8b21cc',
    messagingSenderId: '829328918053',
    projectId: 'femclock',
    storageBucket: 'femclock.firebasestorage.app',
    iosBundleId: 'com.example.femClock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6c8BBUKj2c0LQvpkZTbujFpA-ZkCVpsI',
    appId: '1:829328918053:ios:1cf7f2de7ea6089f8b21cc',
    messagingSenderId: '829328918053',
    projectId: 'femclock',
    storageBucket: 'femclock.firebasestorage.app',
    iosBundleId: 'com.example.femClock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD52d4IGTra0J33REeqwisaWkF4SoPtaqM',
    appId: '1:829328918053:web:919c56fcf21fb9c68b21cc',
    messagingSenderId: '829328918053',
    projectId: 'femclock',
    authDomain: 'femclock.firebaseapp.com',
    storageBucket: 'femclock.firebasestorage.app',
  );

}